# Dependencies
markdown:         redcarpet
highlighter: rouge    

# Permalinks
permalink:        pretty

# Setup
title:            /Code/Blog
tagline:          'Play ground of learning'
description:      '.NET/Sharepoint developer from Bangladesh <a href="https://facebook.com/logicalforhad" target="_blank">@logicalforhad</a>.'
url:              http://logicalforhad.wordpress.com
baseurl:          /

author:
  name:           'S.M. Forhad Ali'
  url:            https://twitter.com/_iLogical

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
# Gems
gems: [jekyll-paginate]